export default {
  container: {
    // flex: 1,
    backgroundColor: 'rgba(253, 252, 252, 1)',
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    justifyContent: 'center',
    padding: 10,
  },
  container2: {
    // flex: 1,
    backgroundColor: 'rgba(253, 252, 252, 1)',
    borderRadius: 15,
    justifyContent: 'center',
    padding: 10,
    margin: 20,
    borderWidth: 0.1,
  },
  toastView: {
    backgroundColor: 'rgba(253, 252, 252, 1)',
    marginHorizontal: 20,
    padding: 10,
    borderRadius: 15,
    elevation: 10,
    marginVertical: 10,
  },
  houseImg: {width: '100%', height: 150},
  distanceClick: {
    backgroundColor: '#fff',
    borderRadius: 5,
    width: 100,
    padding: 2,
    borderColor: 'black',
    borderWidth: 1,
    marginLeft: 3,
    marginRight: 3,
  },
  nearBy: {
    display: 'flex',
    textAlign: 'center',
    // fontWeight: 'bold',
    color: 'black',
    fontSize: 10,
    fontFamily: 'BlissPro-Bold',
  },
  bhk: {
    margin: 10,
    fontFamily: 'BlissPro-Bold',
    color: 'black',
    fontSize: 15,
    marginRight: 3,
    marginLeft: 3,
    // fontWeight: 'bold',
  },
  btnContainer: {
    backgroundColor: '#fff',
    borderRadius: 15,
    padding: 10,
    elevation: 5,
    marginLeft: 5,
    marginRight: 5,
  },
  btnTxt: {
    display: 'flex',
    textAlign: 'center',
    color: 'black',
    fontSize: 15,
    fontFamily: 'math',
  },
};
