export default {
  container: {
    backgroundColor: 'rgba(253, 252, 252, 1)',
    borderRadius: 20,
  },
  houseImg: {
    width: '100%',
    height: 250,
    // padding: 10,
  },
  inputField: {
    marginTop: 15,
    marginBottom: 5,
    marginLeft: 10,
    marginRight: 10,
  },
  loginBtn: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#A5DE18',
    margin: 10,
    borderRadius: 5,
  },
  lgnbtnTxt: {
    fontFamily: 'serif',
    marginLeft: 12,
    textAlign: 'center',
    color: 'black',
  },
  toastTxt: {
    textAlign: 'center',
    color: 'white',
    padding: 10,
    fontSize: 12,
    fontFamily: 'serif',
    fontWeight: 'bold',
  },
  errorMsg: {
    color: 'red',
    marginLeft: 15,
    fontFamily: 'serif',
  },
  bhk: {
    margin: 10,
    fontFamily: 'serif',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 15,
    marginRight: 3,
    marginLeft: 3,
  },
  distanceClick: {
    backgroundColor: '#fff',
    borderRadius: 5,
    width: 100,
    padding: 2,
    borderColor: 'black',
    borderWidth: 1,
    marginLeft: 3,
    marginRight: 3,
  },
  nearBy: {
    display: 'flex',
    textAlign: 'center',
    fontWeight: 'bold',
    color: 'black',
    fontSize: 10,
    fontFamily: 'math',
  },
  shortAdd: {
    textAlign: 'center',
    fontFamily: 'math',
    fontSize: 16,
    margin: 10,
    color: 'black',
    fontWeight: 'bold',
  },
  addRess: {
    textAlign: 'center',
    fontFamily: 'math',
    fontSize: 20,
    margin: 10,
    color: 'black',
    fontWeight: 'bold',
  },
  container3: {
    // flex: 1,
    backgroundColor: '#EBF4FA',
    borderRadius: 8,
    justifyContent: 'center',
    padding: 10,
    margin: 20,
    elevation: 5,
    overflow: 'hidden',
  },
  mapcontainer: {
    height: 600,
    width: '80%',
    padding: 20,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  btnContainer: {
    backgroundColor: '#fff',
    borderRadius: 5,
    // width: '100%',
    padding: 10,
    elevation: 10,
    marginVertical: 10,
  },
  btnTxt: {
    display: 'flex',
    textAlign: 'center',
    color: 'black',
    fontSize: 15,
    fontFamily: 'math',
  },
};
